---
- name: Install and configure AIDE
  apt:
    name: aide
    state: present
  notify: initialize aide

- name: Deploy AIDE config
  template:
    src: aide/aide.conf.j2
    dest: /etc/aide/aide.conf
