---
- name: Install monitoring stack
  apt:
    name: ["prometheus", "grafana", "prometheus-node-exporter"]
    state: present

- name: Deploy monitoring configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'prometheus/prometheus.yml.j2', dest: '/etc/prometheus/prometheus.yml' }
    - { src: 'grafana/datasources.yml.j2', dest: '/etc/grafana/provisioning/datasources/prometheus.yml' }
  notify: restart monitoring services
