---
- name: Install monitoring stack
  apt:
    name: ["prometheus", "grafana", "prometheus-node-exporter"]
    state: present

- name: Deploy Prometheus config
  template:
    src: prometheus/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: Deploy Grafana config
  template:
    src: grafana/datasources.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
  notify: restart grafana

- name: Enable monitoring services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - prometheus
    - grafana
    - prometheus-node-exporter
