---
- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Configure Redis
  template:
    src: redis/redis.conf.j2
    dest: /etc/redis/redis.conf
  notify: restart redis

- name: Enable Redis
  systemd:
    name: redis-server
    enabled: yes
    state: restarted
