---
- name: Configure Roundcube
  template:
    src: roundcube/config.inc.php.j2
    dest: /etc/roundcube/config.inc.php

- name: Initialize Roundcube database
  mysql_db:
    name: "{{ roundcube_db_name }}"
    state: import
    target: /usr/share/roundcube/SQL/mysql.initial.sql

- name: Set Roundcube permissions
  file:
    path: /var/lib/roundcube
    owner: www-data
    group: www-data
    recurse: yes
