---
- name: Create mail users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: vmail
    shell: /usr/sbin/nologin
  loop: "{{ mail_users }}"
  no_log: true

- name: Create mail directories
  file:
    path: "/var/mail/vhosts/{{ domain }}/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: vmail
    mode: 0700
  loop: "{{ mail_users }}"
