---
- name: Add Incus repository
  apt_repository:
    repo: deb [arch=amd64] https://ubuntu.com/incus/static/stable/debian/ bookworm incus
    state: present

- name: Install Incus
  apt:
    name: incus
    state: present
    update_cache: yes

- name: Initialize Incus with dir backend
  command: incus init --storage-backend dir --auto

- name: Launch Debian 12 container
  command: incus launch images:debian/12 mailcontainer -c security.nesting=true

- name: Configure container networking
  command: incus config device set mailcontainer eth0 ipv4.address {{ container_ip }}

- name: Install nftables on host
  apt:
    name: nftables
    state: present

- name: Configure host firewall
  template:
    src: host_nftables.conf.j2
    dest: /etc/nftables.conf
  notify: restart nftables

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
