---
- name: restart monitoring services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - prometheus
    - grafana

- name: restart redis
  systemd:
    name: redis-server
    state: restarted

- name: initialize aide
  command: aideinit -y -f
