
- name: restart monitoring services
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - prometheus
    - grafana

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: restart grafana
  systemd:
    name: grafana
    state: restarted

- name: restart redis
  systemd:
    name: redis-server
    state: restarted
